package grade

import org.junit.jupiter.api.*

import core.Database
import model.Table
import structure.SimpleResponse

class Module1 extends AbstractModule {
	@BeforeAll
	static void setup() {
		module_tag = 'M1'
		
		query_data = [
			// CREATE TABLE, GENERAL
			[ true,  'CREATE TABLE m1_table01 (id INTEGER PRIMARY, name STRING, flag BOOLEAN)', null ],
			
			// CREATE TABLE, SYNTAX: CASE AND WHITESPACE
			[ true,  'create table m1_table02 (ID integer primary, NAME string, flag BOOLEAN)', 'lowercase keywords and uppercase table names are allowed' ],
			[ true,  ' CREATE TABLE m1_table03 (id INTEGER PRIMARY, name STRING, flag BOOLEAN) ', 'untrimmed whitespace is allowed' ],
			[ true,  'CREATE  TABLE  m1_table04  (id INTEGER PRIMARY, name STRING, flag BOOLEAN)', 'excess internal whitespace is allowed' ],
			[ true,  'CREATE TABLE m1_table05 ( id INTEGER PRIMARY , name STRING , flag BOOLEAN )', 'excess internal whitespace is allowed' ],
			[ true,  'CREATE TABLE m1_table06 (id INTEGER PRIMARY,name STRING,flag BOOLEAN)', 'whitespace around punctuation is not required' ],
			[ false, 'CREATETABLE m1_table07 (id INTEGERPRIMARY, name STRING, flag BOOLEAN)', 'whitespace between keywords is required ' ],
			[ false, 'CREATE TABLEm1_table08 (idINTEGER PRIMARY, nameSTRING, flag BOOLEAN)', 'whitespace between keywords and names is required' ],
			
			// CREATE TABLE, SYNTAX: NAMES AND KEYWORDS
			[ true,  'CREATE TABLE t (i INTEGER PRIMARY, n STRING, f BOOLEAN)', 'names can be 1 letter' ],
			[ true,  'CREATE TABLE m1_table10_____ (n23456789012345 INTEGER PRIMARY)', 'names can be up to 15 characters' ],
			[ false, 'CREATE TABLE m1_table11______ (n234567890123456 INTEGER PRIMARY)', 'names can be no more than 15 characters' ],
			[ false, 'CREATE TABLE 1m_table12 (2id INTEGER PRIMARY, 3name STRING, 4flag BOOLEAN)', 'a name cannot start with a number' ],
			[ false, 'CREATE TABLE _m1table13 (_id INTEGER PRIMARY, _name STRING, _flag BOOLEAN)', 'a name cannot start with an underscore' ],
			[ false, 'CREATE TABLE (id INTEGER PRIMARY, name STRING, flag BOOLEAN)', 'the table name cannot be omitted' ],
			[ false, 'CREATE m1_table15 (id INTEGER PRIMARY, name STRING, flag BOOLEAN)', 'the TABLE keyword is required' ],
			
			// CREATE TABLE, SYNTAX: PUNCTUATION AND QUANTITY
			[ false, 'CREATE TABLE m1_table16 (id INTEGER PRIMARY name STRING flag BOOLEAN)', 'the commas between definitions are required' ],
			[ false, 'CREATE TABLE m1_table17 id INTEGER PRIMARY, name STRING, flag BOOLEAN', 'the parentheses are required' ],
			[ false, 'CREATE TABLE m1_table18 ()', 'there must be at least one column' ],
			[ true,  'CREATE TABLE m1_table19 (c1 INTEGER PRIMARY)', 'a single column is allowed' ],
			[ true,  'CREATE TABLE m1_table20 (c1 INTEGER PRIMARY, c2 STRING)', 'two columns are allowed' ],
			[ true,  'CREATE TABLE m1_table21 (c1 INTEGER PRIMARY, c2 INTEGER, c3 INTEGER, c4 INTEGER, c5 INTEGER, c6 INTEGER, c7 INTEGER, c8 INTEGER, c9 INTEGER, c10 INTEGER, c11 INTEGER, c12 INTEGER, c13 INTEGER, c14 INTEGER, c15 INTEGER)', 'up to 15 columns are allowed' ],
			[ false, 'CREATE TABLE m1_table22 (c1 INTEGER PRIMARY, c2 INTEGER, c3 INTEGER, c4 INTEGER, c5 INTEGER, c6 INTEGER, c7 INTEGER, c8 INTEGER, c9 INTEGER, c10 INTEGER, c11 INTEGER, c12 INTEGER, c13 INTEGER, c14 INTEGER, c15 INTEGER, c16 INTEGER)', 'more than 15 columns are not allowed' ],
			
			// CREATE TABLE, SEMANTICS
			[ false, 'CREATE TABLE m1_table23 (id INTEGER, name STRING, flag BOOLEAN)', 'there must be a primary column' ],
			[ false, 'CREATE TABLE m1_table24 (id INTEGER PRIMARY, name STRING PRIMARY, flag BOOLEAN PRIMARY)', 'there can be only one primary column' ],
			[ true,  'CREATE TABLE m1_table25 (id INTEGER, name STRING PRIMARY, flag BOOLEAN)', 'the primary column need not be the first' ],
			[ false, 'CREATE TABLE m1_table01 (ps STRING PRIMARY)', 'the table name must not already be in use' ],
			
			// DROP TABLE, GENERAL
			[ true,  'DROP TABLE m1_table01', null ],
			
			// DROP TABLE, SYNTAX: CASE AND WHITESPACE
			[ true,  'drop table m1_table02', 'lowercase keywords and uppercase table names are allowed' ],
			[ true,  ' DROP TABLE m1_table03 ', 'untrimmed whitespace is allowed' ],
			[ true,  'DROP  TABLE  m1_table04', 'excess internal whitespace is allowed' ],
			[ false, 'DROPTABLE m1_table05', 'whitespace between keywords is required ' ],
			[ false, 'DROP TABLEm1_table06', 'whitespace between keywords and names is required' ],
			
			// DROP TABLE, SYNTAX: NAMES AND KEYWORDS
			[ true,  'DROP TABLE t', 'names can be a single letter' ],
			[ false, 'DROP TABLE', 'the table name cannot be omitted' ],
			[ false, 'DROP m1_table17', 'the TABLE keyword is required' ],
			
			// DROP TABLE AND CREATE TABLE, SEMANTICS
			[ false, 'DROP TABLE m1_table01', 'the table must already exist' ],
			[ true,  'CREATE TABLE m1_table01 (ps STRING PRIMARY)', 'previously dropped table name can be reused' ],
			
			// SHOW TABLES, GENERAL
			[ true,  'SHOW TABLES', null ],
			
			// SHOW TABLES, SYNTAX
			[ true,  'show tables', 'lowercase keywords are allowed' ],
			[ true,  ' SHOW TABLES ', 'untrimmed whitespace is allowed' ],
			[ true,  'SHOW  TABLES', 'excess internal whitespace is allowed' ],
			[ false, 'SHOWTABLES', 'whitespace between keywords is required ' ],
			[ false, 'SHOW', 'the TABLES keyword is required' ],
			
			// UNRECOGNIZED AND SCRIPTS, GENERAL
			[ false, 'AN INVALID QUERY', 'an unrecognized query should be rejected' ],
			[ true,  'ECHO "Test1"; RANGE 10; ECHO "Test2"', 'multiple semicolon-delimited queries are allowed' ],
		]
		
		computed_schemas = [
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			['table_name':'m1_table19', 'column_names':['c1'], 'column_types':['integer'], 'primary_index':0],
			['table_name':'m1_table20', 'column_names':['c1', 'c2'], 'column_types':['integer', 'string'], 'primary_index':0],
			['table_name':'m1_table21', 'column_names':['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15'], 'column_types':['integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer'], 'primary_index':0],
			null,
			null,
			null,
			['table_name':'m1_table25', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':1],
			null,
			['table_name':'m1_table01', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table02', 'column_names':['ID', 'NAME', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table03', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table04', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			null,
			null,
			['table_name':'t', 'column_names':['i', 'n', 'f'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			null,
			null,
			null,
			['table_name':'m1_table01', 'column_names':['ps'], 'column_types':['string'], 'primary_index':0],
			['table_name':'_tables', 'column_names':['table_name', 'row_count'], 'column_types':['string', 'integer'], 'primary_index':0],
			['table_name':'_tables', 'column_names':['table_name', 'row_count'], 'column_types':['string', 'integer'], 'primary_index':0],
			['table_name':'_tables', 'column_names':['table_name', 'row_count'], 'column_types':['string', 'integer'], 'primary_index':0],
			['table_name':'_tables', 'column_names':['table_name', 'row_count'], 'column_types':['string', 'integer'], 'primary_index':0],
			null,
			null,
			null,
			null,
		]

		computed_states = [
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			[:],
			[:],
			[:],
			null,
			null,
			null,
			[:],
			null,
			[:],
			[:],
			[:],
			[:],
			null,
			null,
			[:],
			null,
			null,
			null,
			[:],
			['m1_table25':['m1_table25', 0], 'm1_table05':['m1_table05', 0], 'm1_table06':['m1_table06', 0], 'm1_table01':['m1_table01', 0], 'm1_table10_____':['m1_table10_____', 0], 'm1_table20':['m1_table20', 0], 'm1_table21':['m1_table21', 0], 'm1_table19':['m1_table19', 0]],
			['m1_table25':['m1_table25', 0], 'm1_table05':['m1_table05', 0], 'm1_table06':['m1_table06', 0], 'm1_table01':['m1_table01', 0], 'm1_table10_____':['m1_table10_____', 0], 'm1_table20':['m1_table20', 0], 'm1_table21':['m1_table21', 0], 'm1_table19':['m1_table19', 0]],
			['m1_table25':['m1_table25', 0], 'm1_table05':['m1_table05', 0], 'm1_table06':['m1_table06', 0], 'm1_table01':['m1_table01', 0], 'm1_table10_____':['m1_table10_____', 0], 'm1_table20':['m1_table20', 0], 'm1_table21':['m1_table21', 0], 'm1_table19':['m1_table19', 0]],
			['m1_table25':['m1_table25', 0], 'm1_table05':['m1_table05', 0], 'm1_table06':['m1_table06', 0], 'm1_table01':['m1_table01', 0], 'm1_table10_____':['m1_table10_____', 0], 'm1_table20':['m1_table20', 0], 'm1_table21':['m1_table21', 0], 'm1_table19':['m1_table19', 0]],
			null,
			null,
			null,
			null,
		]

		stored_schemas = [
			['table_name':'m1_table01', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table02', 'column_names':['ID', 'NAME', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table03', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table04', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table05', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table06', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			null,
			null,
			['table_name':'t', 'column_names':['i', 'n', 'f'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			['table_name':'m1_table10_____', 'column_names':['n23456789012345'], 'column_types':['integer'], 'primary_index':0],
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			['table_name':'m1_table19', 'column_names':['c1'], 'column_types':['integer'], 'primary_index':0],
			['table_name':'m1_table20', 'column_names':['c1', 'c2'], 'column_types':['integer', 'string'], 'primary_index':0],
			['table_name':'m1_table21', 'column_names':['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13', 'c14', 'c15'], 'column_types':['integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer', 'integer'], 'primary_index':0],
			null,
			null,
			null,
			['table_name':'m1_table25', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':1],
			['table_name':'m1_table01', 'column_names':['id', 'name', 'flag'], 'column_types':['integer', 'string', 'boolean'], 'primary_index':0],
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			['table_name':'m1_table01', 'column_names':['ps'], 'column_types':['string'], 'primary_index':0],
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
		]

		stored_states = [
			[:],
			[:],
			[:],
			[:],
			[:],
			[:],
			null,
			null,
			[:],
			[:],
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			[:],
			[:],
			[:],
			null,
			null,
			null,
			[:],
			[:],
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			[:],
			null,
			null,
			null,
			null,
			null,
			null,
			null,
			null,
		]
	}
}